### ISSUE TITLE
Error while setting up epg platform for sensor

### ISSUE THREAD

**Issue by H3rian** [yohaybn/HomeAssistant-EPG#3]
From a couple of days i'm keep receving this error. None of the sensor works.
I'm on 2024.9.1

```
Registratore: homeassistant.components.sensor
Fonte: helpers/entity_platform.py:361
Integrazione: Sensore (documentazione, problemi)
Prima occorrenza: 20:40:27 (1 occorrenze)
Ultima registrazione: 20:40:27

Error while setting up epg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/epg/sensor.py", line 92, in async_setup_platform
    entities.append(ChannelSensor(hass,_config, channel.name(), channel))
                                                ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by H3rian** [comment]
Solved, problem on my hand
