### ISSUE TITLE
Detected blocking call to open with args

### ISSUE THREAD

**Issue by rosentrieb** [yohaybn/HomeAssistant-EPG#6]
Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 13:21:44 (1 Vorkommnisse)
Zuletzt protokolliert: 13:21:44

Detected blocking call to open with args ('/usr/local/lib/python3.13/site-packages/pytz/zoneinfo/Europe/Berlin', 'rb') inside the event loop by custom integration 'epg' at custom_components/epg/guide_classes.py, line 131: self.TIMEZONE=pytz.timezone(time_zone) (offender: /usr/local/lib/python3.13/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/yohaybn/HomeAssistant-EPG/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/epg/sensor.py", line 84, in async_setup_platform guide = await get_guide(hass, _config, row) File "/config/custom_components/epg/sensor.py", line 140, in get_guide guide = Guide(content,hass.config.time_zone) File "/config/custom_components/epg/guide_classes.py", line 131, in __init__ self.TIMEZONE=pytz.timezone(time_zone)

**Comment by yohaybn** [comment]
Hi,
I fixed the issue, please update to latest version and check.
thank you for the issue!
